<<<<<<< HEAD:old-frontend-1/src/app/layout.tsx
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/contexts/AuthContext';
// import { CartProvider } from '@/contexts/CartContext';
// import { WishlistProvider } from '@/contexts/WishlistContext';
import { ToastProvider } from '@/contexts/ToastContext';
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
>>>>>>> frontend-setup:frontend/src/app/layout.tsx

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD:old-frontend-1/src/app/layout.tsx
        <ToastProvider>
          <AuthProvider>
            {/* <CartProvider> */}
            {/* <WishlistProvider>{children}</WishlistProvider> */}
            {children}
            {/* </CartProvider> */}
          </AuthProvider>
        </ToastProvider>
=======
        {children}
>>>>>>> frontend-setup:frontend/src/app/layout.tsx
      </body>
    </html>
  );
}
